name: Simona Glombíková, Webové publikovanie
permalink: /projects/:title
title: SIMfólio

collections:
  devtechs:
    output: true
  projects:
    output: true
slideshow:
    width: 150
    height: 100
